apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 31002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - env:
            - name: DB_SERVER
              value: database
            - name: MYSQL_DATABASE
              value: pizzeria_db
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: "root"
          image: sokols/comment-service
          name: comment-service
          ports:
            - name: http
              containerPort: 8080
